sudo: required
services:
  - docker

env:
  global:
    - secure: "DqrBa11t057wK6mEsojA78YUrGiXvqPnyhRtcQuccKf+IXbsj4l+nUw1luJxRxUryrmMscpbkesDI7PFUvXv0n45aIglhOBDZ82a0vOu+ASC4ox0VVNaB9aUtzv+391E9JtKKvn+jGULj+zPEDc6kqOOHE+L9jhtOzmMiQkphPftR742S4PN6LJyaCcpaaEvTH+WyKPOU5h8MWwEP0jAKKzMeVWCgxFot6QTVd4z6EM+mF8tcXU837seTk/zrSg+4YIob/Qw71FHOTCBpKgJQMcN7VfyD7JmBqrNnG/9ViVCiwEidjMS0JetbZ0xhM8FIz/ddCkoZFrF22NJbiQcXSVzTmDOaPloAnRgmnLzAYswXsmf1akOs5Xls6yVKxry6dhYeNZldP6VIiq1lWRmEz2sTEQzlAODNXa1U4KhgU0W1L1ylUwFDb++jYEGt/Zu+5F7Q4bZu9IRxXgknNdIfatbgOTLudGTmLh622Gidics1Dh0oLx0Y7OUX9simWPwmMAnPt4w1mykb2AWclhug5pGYt1Zw6mAlanqCUdqqQg4N0ZnZjZ4nwza1wZiNRjam/x6pbEE4gtiwkVNMRpRojaMEBjobq1JmYPhAD9Xgbxh1JxUXfHijh2hS5n8KbqhxuaEjR0b+2/2IIS3pXKR9QokOxqdRWg42S1eu2Ce98U="

language: go
go: 1.8

install:
  - curl https://glide.sh/get | sh
script:
  - glide install
  - go test -v -cover
  - go vet -x
  - mkdir -p bin
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_amd64
  - GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_386
  - GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_arm
  - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_darwin_amd64
  - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_windows_amd64.exe
  - if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_EVENT_TYPE} == "push" ]]) || [[ -n ${TRAVIS_TAG} ]]; then
    docker login -u "ukhomeofficedigital+kubernetes_deploy_kd" -p ${DOCKER_PASSWORD} quay.io;
    docker build -t quay.io/ukhomeofficedigital/kd:${TRAVIS_TAG:-latest} .;
    docker push quay.io/ukhomeofficedigital/kd:${TRAVIS_TAG:-latest};
    fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JdURCNO9Q7I1bl4akrEBT03RfPd5WYVZOSiyt+X9sSvbutpUe5AsrFUjnPwNYj5F0N7abtAX+O938SimIrNcUJnzVvB+RbOUHmhNQda9Qjri71yyj1M/IDS/KSenfTsXI+S5JS1bGAAIcUPTktYQqm+4veLmeLpyWUdaZcb1II2eGDMsUBSr1T3dLjZ6oNzO82V2YCwjBvaldJAroNiOQr5pAcjloOIwKkQWChHBzQwUkFQP/CbIMh17d0WRHQ77sscLiQtUWsC4VsZOybQK+q85vPjFid7asmHWM1UoAeKmWcu6IimVs0Yo9IPj3vVIK708zPs6XNJHCHcBUjJDSDCQyLLx8PFc105YOLwyKqWEAPr/okE62vtR4k91khwUl6NEM08ACqm7mnQiQvO2NEyEbnEDoQYTxBD1GyrLQ93NeVTbK7hCPdoNXHikbfwmWMqPANYCFF4b1jb+dYiREqRvn97zNxTVw/fDk5BVS4uFMxfiyECivXmSs0IXEOpxU8uvOJ6aJxzy+C9HMQrFPwUEqRajepqmhgoR1CTXlwrLNK7zull5Fa/DMYKOrLuJswXG+ARk9HMRHEK5b0ys8WxYIMxE9Sy3yUYb5qa1RfVdDOU3XtBAbP/PzvXDTGFAzrFxBbJPKaqv6pMGPrDHgqpCXgYEt11vnSzJPgYIEgg=
  file:
    - ${TRAVIS_BUILD_DIR}/bin/kd_linux_amd64
    - ${TRAVIS_BUILD_DIR}/bin/kd_linux_386
    - ${TRAVIS_BUILD_DIR}/bin/kd_linux_arm
    - ${TRAVIS_BUILD_DIR}/bin/kd_darwin_amd64
    - ${TRAVIS_BUILD_DIR}/bin/kd_windows_amd64.exe
  on:
    tags: true
    repo: UKHomeOffice/kd
