sudo: required
services:
  - docker

env:
  global:
    - secure: "cLpRQqYGOGH9AOL5xc9flk0H/dmBlo984fDbLn64TKtQ1/JJJxx+drjChjJ2zMHMs3o3qDuG+K1eS9vGTvJ7KGhFRZN4JeZSilC1UrRNujXHtFTL2D4qex4AlLCj9Rh1ZdZVs5MbLr3yEi7PZkF8r/wytlH+Vb+FHFll8tDbCMzrjyEatXj6LOlRtWdajerKeNQAMUWG3fJOHu0hhQcT/dxEwt7O9M+6Dx5mnfRVrx7pKorlgFWEfuHE2xncAIUrevfH7Rv13ybD6gO/MIux9JmObmeV1BKQDxKHYt+puDTEFA6G3czgnCCSdpLRbf8fPKcHubTjdsBSqcLyl+/cDAy54lA7fqtZ64BiTz3npEFFGLNxmDORLhb50CHb78+voOwNNxf3JQkqzITT5al2Cgs8StWWBOTk9318yaps2qL+qyRhwB2QC7q5xXktFDQZc9vHF8pDrAoSTzOZtYzp940Syv00dWkqJovxtEDO+5FBYbxSyE2UB2pn4wYyh8TT2mQfsZHPpKW5tY7U4zibaqmLxN0MSoKA1+VV7tRDyZwsv4MIDH3hHzHLx5szUZAbG2qEtS/Ed6MN1QJOZ3pBpV6PxRJ3UKAVHq8Pe32RzUuSVKeXOCPn4V5DKgJQZuSPn+rsRTPt4r9dtSodzQFSQT6QHWGDAqUnLFYvbddNgxQ="

language: go
go: 1.8

install:
  - curl https://glide.sh/get | sh
script:
  - glide install
  - go test -v -cover
  - go vet -x
  - mkdir -p bin
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_amd64
  - GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_386
  - GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_arm
  - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_darwin_amd64
  - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_windows_amd64.exe
  - if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_EVENT_TYPE} == "push" ]]) || [[ -n ${TRAVIS_TAG} ]]; then
    docker login -u "ukhomeofficedigital+kubernetes_deploy_kd" -p ${DOCKER_PASSWORD} quay.io;
    docker build -t quay.io/ukhomeofficedigital/kd:${TRAVIS_TAG:-latest} .;
    docker push quay.io/ukhomeofficedigital/kd:${TRAVIS_TAG:-latest};
    fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JdURCNO9Q7I1bl4akrEBT03RfPd5WYVZOSiyt+X9sSvbutpUe5AsrFUjnPwNYj5F0N7abtAX+O938SimIrNcUJnzVvB+RbOUHmhNQda9Qjri71yyj1M/IDS/KSenfTsXI+S5JS1bGAAIcUPTktYQqm+4veLmeLpyWUdaZcb1II2eGDMsUBSr1T3dLjZ6oNzO82V2YCwjBvaldJAroNiOQr5pAcjloOIwKkQWChHBzQwUkFQP/CbIMh17d0WRHQ77sscLiQtUWsC4VsZOybQK+q85vPjFid7asmHWM1UoAeKmWcu6IimVs0Yo9IPj3vVIK708zPs6XNJHCHcBUjJDSDCQyLLx8PFc105YOLwyKqWEAPr/okE62vtR4k91khwUl6NEM08ACqm7mnQiQvO2NEyEbnEDoQYTxBD1GyrLQ93NeVTbK7hCPdoNXHikbfwmWMqPANYCFF4b1jb+dYiREqRvn97zNxTVw/fDk5BVS4uFMxfiyECivXmSs0IXEOpxU8uvOJ6aJxzy+C9HMQrFPwUEqRajepqmhgoR1CTXlwrLNK7zull5Fa/DMYKOrLuJswXG+ARk9HMRHEK5b0ys8WxYIMxE9Sy3yUYb5qa1RfVdDOU3XtBAbP/PzvXDTGFAzrFxBbJPKaqv6pMGPrDHgqpCXgYEt11vnSzJPgYIEgg=
  file:
    - ${TRAVIS_BUILD_DIR}/bin/kd_linux_amd64
    - ${TRAVIS_BUILD_DIR}/bin/kd_linux_386
    - ${TRAVIS_BUILD_DIR}/bin/kd_linux_arm
    - ${TRAVIS_BUILD_DIR}/bin/kd_darwin_amd64
    - ${TRAVIS_BUILD_DIR}/bin/kd_windows_amd64.exe
  on:
    tags: true
    repo: UKHomeOffice/kd
