sudo: required
services:
  - docker

env:
  global:
    - secure: "DqrBa11t057wK6mEsojA78YUrGiXvqPnyhRtcQuccKf+IXbsj4l+nUw1luJxRxUryrmMscpbkesDI7PFUvXv0n45aIglhOBDZ82a0vOu+ASC4ox0VVNaB9aUtzv+391E9JtKKvn+jGULj+zPEDc6kqOOHE+L9jhtOzmMiQkphPftR742S4PN6LJyaCcpaaEvTH+WyKPOU5h8MWwEP0jAKKzMeVWCgxFot6QTVd4z6EM+mF8tcXU837seTk/zrSg+4YIob/Qw71FHOTCBpKgJQMcN7VfyD7JmBqrNnG/9ViVCiwEidjMS0JetbZ0xhM8FIz/ddCkoZFrF22NJbiQcXSVzTmDOaPloAnRgmnLzAYswXsmf1akOs5Xls6yVKxry6dhYeNZldP6VIiq1lWRmEz2sTEQzlAODNXa1U4KhgU0W1L1ylUwFDb++jYEGt/Zu+5F7Q4bZu9IRxXgknNdIfatbgOTLudGTmLh622Gidics1Dh0oLx0Y7OUX9simWPwmMAnPt4w1mykb2AWclhug5pGYt1Zw6mAlanqCUdqqQg4N0ZnZjZ4nwza1wZiNRjam/x6pbEE4gtiwkVNMRpRojaMEBjobq1JmYPhAD9Xgbxh1JxUXfHijh2hS5n8KbqhxuaEjR0b+2/2IIS3pXKR9QokOxqdRWg42S1eu2Ce98U="

language: go
go: 1.6

install: true
script:
  - go test -v -cover
# Only go build binaries when branch is master and not a PR
  - if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} != "true" ]]) || [[ -n ${TRAVIS_TAG} ]]; then
    mkdir -p bin;
    GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_amd64;
    GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_386;
    GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_linux_arm;
    GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_darwin_amd64;
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/kd_windows_amd64.exe;
    docker login -u "ukhomeofficedigital+kubernetes_deploy_kd" -p ${DOCKER_PASSWORD} quay.io;
    docker build -t quay.io/ukhomeofficedigital/kd:${TRAVIS_TAG:-latest} .;
    docker push quay.io/ukhomeofficedigital/kd:${TRAVIS_TAG:-latest};
    fi
deploy:
  provider: releases
  api_key:
    secure: "Z0VPkgJ2TYY2E66Z3Np2CmIOiSb6jfTtKAijmjyP9BNprxQpqpTIGch1RU3tFRj79rab7lOCJ/jUr4F1pOth4JjMWWmhoKLsSEP6KphSgapuh4++TU/9+Qy0hCvOYW5+HP/TozGwFcjEJvD6W3jOZbYh0jbKIFPifXJNraWzKddSaYkww94ZgN/m2sjygO5cOvrvKqwMoBKaKpJWbZ8JMvgBf+jbwtMwbMXMFg4OW4CLMKpRibY7IEQOHHogYV9s+ly32jFyrpFNaP5CMeho6KE3KmJQaYn21mcDSFrBS90xtJGPdJwVbutuPZ04y1J+IypfgIJ7qBxewTRmsxWcn2Ziyg3gwP/bCmVQzOXA8+/ZFaax/WCdbXyzF2kRXlpU23C5lWbtQKO02B657xD6GOs9vB76UjWx9yEpmzV3OwSsqFz0IjMDt6VhjYTtkK30AV2XapykroHgshpug7K7mMdruugU9g6jjRKFyx0ITd6njNFrbBN009DawlRRrOhPoh6dPJ/fu6gbgTyk3AIjKBRlE6U6t97OUiPaLXAAUL/JrHwYvU/PFaNm1kxzvLevqJAIChU2eIViB2tRgdQiEWIyIQEV2KiyoY3w05BscFLB45TiyYkogYaxrvXimFfFx6fXl7Luk1lFNmPqIsH7ttgp+2bagYegNHS1hFGqS00="
  file:
    - bin/kd_linux_amd64
    - bin/kd_linux_386
    - bin/kd_linux_arm
    - bin/kd_darwin_amd64
    - bin/kd_windows_amd64.exe
  on:
    tags: true
    repo: UKHomeOffice/kd
